-- @VERSION: 200100
ALTER TABLE "source" ADD COLUMN "ScriptSrcId" TEXT;
ALTER TABLE "source" ADD COLUMN "Valid" INTEGER DEFAULT 1;
ALTER TABLE "source" ADD COLUMN "Clip" TEXT;
ALTER TABLE "source" ADD COLUMN "URL" TEXT;
ALTER TABLE "source" ADD COLUMN "Tags" TEXT;
