#!/bin/sh
set -e

# Update desktop database
if [ -x "$(command -v update-desktop-database)" ]; then
    update-desktop-database -q /usr/share/applications
fi

# Update icon cache
if [ -x "$(command -v gtk-update-icon-cache)" ]; then
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
fi

# Update mime database
if [ -x "$(command -v update-mime-database)" ]; then
    update-mime-database /usr/share/mime
fi
